export const PROJECTS = [
  {
    id: 1,
    programmeSlug: "bachelor-information-technology-hons",
    name: "Chinedu Okafor",
    psaTitle: "AI-Powered Health Tracker",
    report: "#",
    demo: "#",
    supervisor: "Mr. Jafar",
    year: 2024,
  },
  {
    id: 2,
    programmeSlug: "doctor-of-medicine-md-mbbs",
    name: "Maryam Abdullahi",
    psaTitle: "AI-Assisted Diagnosis System",
    report: "#",
    demo: "#",
    supervisor: "Prof. Bello",
    year: 2024,
  },
  {
    id: 3,
    programmeSlug: "bachelor-information-technology-hons",
    name: "Daniel James",
    psaTitle: "Smart Weather App",
    report: "#",
    demo: "#",
    supervisor: "Mr. Jafar",
    year: 2024,
  },
  {
    id: 4,
    programmeSlug: "bachelor-of-business-administration-hons",
    name: "Grace Uche",
    psaTitle: "E-Commerce Supply Chain Optimizer",
    report: "#",
    demo: "#",
    supervisor: "Dr. Adeyemi",
    year: 2023,
  },
  {
    id: 5,
    programmeSlug: "bachelor-of-arts-mass-communication-hons",
    name: "Olamide Akin",
    psaTitle: "Digital Storytelling for Social Change",
    report: "#",
    demo: "#",
    supervisor: "Prof. Musa",
    year: 2024,
  },
  {
    id: 6,
    programmeSlug: "doctor-of-medicine-md-mbbs",
    name: "Fatima Sule",
    psaTitle: "Mobile App for Rural Health Outreach",
    report: "#",
    demo: "#",
    supervisor: "Dr. Hassan",
    year: 2023,
  },
  {
    id: 7,
    programmeSlug: "bachelor-of-management-oil-and-gas",
    name: "Ibrahim Lawal",
    psaTitle: "Predictive Maintenance in Oil Pipelines",
    report: "#",
    demo: "#",
    supervisor: "Dr. Johnson",
    year: 2024,
  },
  {
    id: 8,
    programmeSlug: "bachelor-information-technology-hons",
    name: "Ngozi Eze",
    psaTitle: "Blockchain-Based Voting System",
    report: "#",
    demo: "#",
    supervisor: "Mr. Jafar",
    year: 2023,
  },
  {
    id: 9,
    programmeSlug: "bachelor-of-business-administration-hons",
    name: "Emeka Obi",
    psaTitle: "AI-Driven Marketing Analytics",
    report: "#",
    demo: "#",
    supervisor: "Dr. Adeyemi",
    year: 2024,
  },
  {
    id: 10,
    programmeSlug: "bachelor-of-arts-mass-communication-hons",
    name: "Ruth Adebanjo",
    psaTitle: "Podcast Platform for Campus News",
    report: "#",
    demo: "#",
    supervisor: "Prof. Musa",
    year: 2023,
  },
  {
    id: 11,
    programmeSlug: "doctor-of-medicine-md-mbbs",
    name: "Yakubu Idris",
    psaTitle: "Wearable ECG Monitoring Device",
    report: "#",
    demo: "#",
    supervisor: "Dr. Bello",
    year: 2024,
  },
  {
    id: 12,
    programmeSlug: "bachelor-information-technology-hons",
    name: "Blessing Ekpo",
    psaTitle: "Campus Navigation App",
    report: "#",
    demo: "#",
    supervisor: "Engr. Adebayo",
    year: 2023,
  },
  {
    id: 13,
    programmeSlug: "bachelor-of-business-administration-hons",
    name: "Tunde Akpan",
    psaTitle: "Microfinance App for Small Businesses",
    report: "#",
    demo: "#",
    supervisor: "Dr. Adeyemi",
    year: 2024,
  },
  {
    id: 14,
    programmeSlug: "bachelor-of-management-oil-and-gas",
    name: "Hauwa Danjuma",
    psaTitle: "Green Energy Transition Framework",
    report: "#",
    demo: "#",
    supervisor: "Dr. Johnson",
    year: 2023,
  },
  {
    id: 15,
    programmeSlug: "bachelor-of-arts-mass-communication-hons",
    name: "Samuel Etim",
    psaTitle: "AI-Powered Fake News Detector",
    report: "#",
    demo: "#",
    supervisor: "Prof. Musa",
    year: 2024,
  },
  {
    id: 16,
    programmeSlug: "bachelor-information-technology-hons",
    name: "Esther John",
    psaTitle: "Smart Home Automation",
    report: "#",
    demo: "#",
    supervisor: "Engr. Adebayo",
    year: 2023,
  },
  {
    id: 17,
    programmeSlug: "doctor-of-medicine-md-mbbs",
    name: "Chika Nnamdi",
    psaTitle: "Telemedicine Platform for Elderly Care",
    report: "#",
    demo: "#",
    supervisor: "Dr. Hassan",
    year: 2024,
  },
  {
    id: 18,
    programmeSlug: "bachelor-of-business-administration-hons",
    name: "Kehinde Ayo",
    psaTitle: "AI-Powered Recruitment System",
    report: "#",
    demo: "#",
    supervisor: "Dr. Adeyemi",
    year: 2023,
  },
  {
    id: 19,
    programmeSlug: "bachelor-information-technology-hons",
    name: "Adeola Ogun",
    psaTitle: "E-Library Management System",
    report: "#",
    demo: "#",
    supervisor: "Mr. Jafar",
    year: 2024,
  },
  {
    id: 20,
    programmeSlug: "bachelor-of-management-oil-and-gas",
    name: "Sadiq Musa",
    psaTitle: "AI-Enhanced Safety Monitoring",
    report: "#",
    demo: "#",
    supervisor: "Dr. Johnson",
    year: 2024,
  },
  {
    id: 21,
    programmeSlug: "bachelor-of-arts-mass-communication-hons",
    name: "Peace Onu",
    psaTitle: "Virtual Reality in Journalism",
    report: "#",
    demo: "#",
    supervisor: "Prof. Musa",
    year: 2023,
  },
  {
    id: 22,
    programmeSlug: "doctor-of-medicine-md-mbbs",
    name: "Hassan Ali",
    psaTitle: "AI for Early Cancer Detection",
    report: "#",
    demo: "#",
    supervisor: "Dr. Bello",
    year: 2024,
  },
  {
    id: 23,
    programmeSlug: "bachelor-information-technology-hons",
    name: "Joy Udo",
    psaTitle: "Crowdsourced Traffic App",
    report: "#",
    demo: "#",
    supervisor: "Engr. Adebayo",
    year: 2023,
  },
  {
    id: 24,
    programmeSlug: "bachelor-of-business-administration-hons",
    name: "Victor Eze",
    psaTitle: "Sustainable Startup Incubator Model",
    report: "#",
    demo: "#",
    supervisor: "Dr. Adeyemi",
    year: 2024,
  },
  {
    id: 25,
    programmeSlug: "bachelor-of-management-oil-and-gas",
    name: "Halima Ibrahim",
    psaTitle: "Renewable Energy Adoption in Oil Firms",
    report: "#",
    demo: "#",
    supervisor: "Dr. Johnson",
    year: 2023,
  },
];
